name: "Surf Forecast"
slug: "surf_forecast_addon"
description: "Surf forecast and metrics for Home Assistant."
version: "1.0.5"
arch:
    - amd64
    - aarch64
init: false
startup: application
boot: auto
ports:
    8080/tcp: null
webui: "http://[HOST]:[PORT:8080]"
ingress: true
ingress_port: 8080
panel_icon: "mdi:waves"
panel_title: "Surf Forecast"

options:
    title: "Surf spots configuration"
    model: "meteofrance_wave"
    spots:
        - id: "carcavelos"
          name: "Carcavelos"
          latitude: 38.6792
          longitude: -9.3353
          cover: "https://images.winalist.com/cdn-cgi/image/format=auto%2Cquality=85%2Cfit=scale-down%2Cwidth=1500/blog/wp-content/uploads/2024/02/21121503/AdobeStock_635919891-1500x844.jpeg"
          facing: 150.0
          region: "Carcavelos"
          swell:
              preferred_min: 200.0
              preferred_max: 290.0
          wind:
              offshore_min: 330.0
              offshore_max: 40.0
        - id: "sao_pedro"
          name: "São Pedro do Estoril"
          latitude: 38.6946
          longitude: -9.3705
          cover: "https://i.ytimg.com/vi/ZxdMqyrMwO0/maxresdefault.jpg"
          facing: 165.0
          region: "Estoril"
          swell:
              preferred_min: 200.0
              preferred_max: 280.0
          wind:
              offshore_min: 330.0
              offshore_max: 30.0
        - id: "fonte_da_telha"
          name: "Fonte da Telha"
          latitude: 38.5684
          longitude: -9.1947
          cover: "https://t3.ftcdn.net/jpg/13/61/34/38/360_F_1361343819_3IQgQ38rNxAHOtNVlNJRXZnoXyL5AnvN.jpg"
          facing: 255.0
          swell:
              preferred_min: 220.0
              preferred_max: 330.0
          wind:
              offshore_min: 50.0
              offshore_max: 110.0
          region: "Almada, PT"
        - id: "sao_joao"
          name: "São João"
          latitude: 38.6517
          longitude: -9.2431
          cover: "https://semmais.pt/wp-content/uploads/2022/08/capa_14109.jpg"
          facing: 270.0
          swell:
              preferred_min: 220.0
              preferred_max: 330.0
          wind:
              offshore_min: 60.0
              offshore_max: 120.0
          region: "Costa de Caparica"
        - id: "guincho"
          name: "Guincho"
          latitude: 38.7327
          longitude: -9.4731
          cover: "https://static-cms.routard.com/web-routard/uploads/xlarge_cascais-guincho-beach.1475511_b748bdf515.jpg"
          facing: 280.0
          region: "Sintra-Cascais"
          swell:
              preferred_min: 210.0
              preferred_max: 340.0
          wind:
              offshore_min: 70.0
              offshore_max: 130.0
schema:
    model: list(ecmwf_wam|ewam|meteofrance_wave)
    spots:
        - id: str
          name: str
          latitude: float(-90.0,90.0)
          longitude: float(-180.0,180.0)
          cover: str
          facing: float
          swell:
              preferred_min: float
              preferred_max: float
          wind:
              offshore_min: float
              offshore_max: float
